apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: syslog
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      timekey: 30s
      timekey_use_utc: true
      timekey_wait: 10s
      flush_interval: 5s
      flush_mode: interval
    format:
      type: out_file
    host: rancher.chfrank.net
    insecure: true
    port: 601
    transport: tcp

